//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch.wuerth.tobias.filehandler.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ch.wuerth.tobias.filehandler.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the root directory for the program to run through.
        /// </summary>
        internal static string FormMain_FolderBrowserDialog_Description {
            get {
                return ResourceManager.GetString("FormMain_FolderBrowserDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start because there is an ambiguous choice between one or more plugins handling the same file extension..
        /// </summary>
        internal static string hint_body_ambiguous_plugin {
            get {
                return ResourceManager.GetString("hint_body_ambiguous_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The /plugins/ directory could not be found. The folder will be created..
        /// </summary>
        internal static string hint_body_no_plugin_folder {
            get {
                return ResourceManager.GetString("hint_body_no_plugin_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin were found in the /plugins/ directory.
        /// </summary>
        internal static string hint_body_no_plugin_found {
            get {
                return ResourceManager.GetString("hint_body_no_plugin_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one plugin has to be selected.
        /// </summary>
        internal static string hint_body_no_plugin_selected {
            get {
                return ResourceManager.GetString("hint_body_no_plugin_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No root directory selected.
        /// </summary>
        internal static string hint_body_no_root_directory {
            get {
                return ResourceManager.GetString("hint_body_no_root_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string hint_head_ambiguous_plugin {
            get {
                return ResourceManager.GetString("hint_head_ambiguous_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading plugins.
        /// </summary>
        internal static string hint_head_no_plugin_folder {
            get {
                return ResourceManager.GetString("hint_head_no_plugin_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string hint_head_no_plugin_found {
            get {
                return ResourceManager.GetString("hint_head_no_plugin_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string hint_head_no_plugin_selected {
            get {
                return ResourceManager.GetString("hint_head_no_plugin_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string hint_head_no_root_directory {
            get {
                return ResourceManager.GetString("hint_head_no_root_directory", resourceCulture);
            }
        }
    }
}
